version: '3.8'

services:
  back:
    build: ./app/back
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  front:
    build: ./app/front
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
